# These are approximate name aliases for GBFR bones found in most humanoid models.
# Feel free to edit the aliases and expand the list for your preferences.

# Since the GBFR bone names are really just indices to bones,
# These only work on humanoid models and this is meant as a quick and dirty utility 
# for converting from/to GBFR/other formats.
# Therefore, do not rely on these for every situation, and do not use them on non-humanoid models.
BONE_NAME_MAPPINGS = {
	"_900": ["Root"],
	"_000": ["Hips", "Waist", "Pelvis"],
	"_001": ["Spine_1", "Spine"],
	"_002": ["Spine_2"],
	"_003": ["Chest", "Upper Chest"],
	"_004": ["Neck"],
	"_a04": ["Neck Deform", "Neck Twist"],
	"_005": ["Head"],
	"_00a": ["Shoulder_L", "Shoulder_Left", "Clavicle_L", "Clavicle_Left", "Left Shoulder"],
	"_006": ["Shoulder_R", "Shoulder_Right", "Clavicle_R", "Clavicle_Right", "Right Shoulder"],
	"_00b": ["Upper Arm_L", "Upper Arm_Left", "Left Arm", "Arm_L", "Arm Left"],
	"_007": ["Upper Arm_R", "Upper Arm_Right", "Right Arm", "Arm_R", "Arm Right"],
	"_a0b": ["Upper Arm Deform_L", "Upper Arm Deform_Left", "Upper Arm Twist_L", "Upper Arm Twist_Left", "Left Arm Deform", "Left Arm Twist", "Arm Deform_L", "Arm Twist_L", "Arm Deform Left", "Arm Twist Left"],
	"_a07": ["Upper Arm Deform_R", "Upper Arm Deform_Right", "Upper Arm Twist_R", "Upper Arm Twist_Right", "Right Arm Deform", "Right Arm Twist", "Arm Deform_R", "Arm Twist_R", "Arm Deform Left", "Arm Twist Right"],
	"_00c": ["Lower Arm_L", "Lower Arm_Left", "Left Lower Arm", "Elbow_L", "Elbow_Left", "Left Elbow"],
	"_008": ["Lower Arm_R", "Lower Arm_Right", "Left Lower Arm", "Elbow_R", "Elbow_Right", "Right Elbow"],
	"_a0c": ["Lower Arm Deform_L", "Lower Arm Deform_Left", "Left Lower Arm Deform", "Elbow Deform_L", "Elbow Deform_Left", "Left Elbow Deform", "Lower Arm Twist_L", "Lower Arm Twist_Left", "Left Lower Arm Twist", "Elbow Twist_L", "Elbow Twist_Left", "Left Elbow Twist"],
	"_a08": ["Lower Arm Deform_R", "Lower Arm Deform_Right", "Left Lower Arm Deform", "Elbow Deform_R", "Elbow Deform_Right", "Right Elbow Deform", "Lower Arm Twist_R", "Lower Arm Twist_Right", "Left Lower Arm Twist", "Elbow Twist_R", "Elbow Twist_Right", "Right Elbow Twist"],
	"_00d": ["Hand_L", "Hand_Left", "Left Hand", "Wrist_L", "Wrist_Left", "Left Wrist"],
	"_009": ["Hand_R", "Hand_Right", "Right Hand", "Wrist_R", "Wrist_Right", "Right Wrist"],
	"_a0d": ["Hand Deform_L", "Hand Deform_Left", "Left Hand Deform", "Wrist Deform_L", "Wrist Deform_Left", "Left Wrist Deform", "Hand Twist_L", "Hand Twist_Left", "Left Hand Twist", "Wrist Twist_L", "Wrist Twist_Left", "Left Wrist Twist"],
	"_a09": ["Hand Deform_R", "Hand Deform_Right", "Right Hand Deform", "Wrist Deform_R", "Wrist Deform_Right", "Right Wrist Deform", "Hand Twist_R", "Hand Twist_Right", "Right Hand Twist", "Wrist Twist_R", "Wrist Twist_Right", "Right Wrist Twist"],
	"_200": ["Thumb Metacarpal_L", "Thumb_01_L"],
	"_201": ["Thumb Proximal_L", "Thumb_02_L"],
	"_202": ["Thumb Distal_L", "Thumb_03_L"],
	"_211": ["Index Proximal_L", "Index_01_L"],
	"_212": ["Index Middle_L", "Index_02_L"],
	"_213": ["Index Distal_L", "Index_03_L"],
	"_221": ["Middle Proximal_L", "Middle_01_L"],
	"_222": ["Middle Middle_L", "Middle_02_L"],
	"_223": ["Middle Distal_L", "Middle_03_L"],
	"_230": ["Ring Metacarpal_L", "Ring_00_L"],
	"_231": ["Ring Proximal_L", "Ring_01_L"],
	"_232": ["Ring Middle_L", "Ring_02_L"],
	"_233": ["Ring Distal_L", "Ring_03_L"],
	"_240": ["Little Metacarpal_L", "Pinky_00_L"],
	"_241": ["Little Proximal_L", "Pinky_01_L"],
	"_242": ["Little Middle_L", "Pinky_02_L"],
	"_243": ["Little Distal_L", "Pinky_03_L"],
	"_100": ["Thumb Metacarpal_R", "Thumb_01_R"],
	"_101": ["Thumb Proximal_R", "Thumb_02_R"],
	"_102": ["Thumb Distal_R", "Thumb_03_R"],
	"_111": ["Index Proximal_R", "Index_01_R"],
	"_112": ["Index Middle_R", "Index_02_R"],
	"_113": ["Index Distal_R", "Index_03_R"],
	"_121": ["Middle Proximal_R", "Middle_01_R"],
	"_122": ["Middle Middle_R", "Middle_02_R"],
	"_123": ["Middle Distal_R", "Middle_03_R"],
	"_130": ["Ring Metacarpal_R", "Ring_00_R"],
	"_131": ["Ring Proximal_R", "Ring_01_R"],
	"_132": ["Ring Middle_R", "Ring_02_R"],
	"_133": ["Ring Distal_R", "Ring_03_R"],
	"_140": ["Little Metacarpal_R", "Pinky_00_R"],
	"_141": ["Little Proximal_R", "Pinky_01_R"],
	"_142": ["Little Middle_R", "Pinky_02_R"],
	"_143": ["Little Distal_R", "Pinky_03_R"],
	"_012": ["Upper Leg_L", "Upper Leg_Left", "Leg_L", "Leg_Left", "Left Leg"],
	"_00e": ["Upper Leg_R", "Upper Leg_Right", "Leg_R", "Leg_Right", "Right Leg"],
	"_a12": ["Upper Leg Deform_L", "Upper Leg Deform_Left", "Leg Deform_L", "Leg Deform_Left", "Left Leg Deform", "Upper Leg Twist_L", "Upper Leg Twist_Left", "Leg Twist_L", "Leg Twist_Left", "Left Leg Twist"],
	"_a0e": ["Upper Leg Deform_R", "Upper Leg Deform_Right", "Leg Deform_R", "Leg Deform_Right", "Right Leg Deform", "Upper Leg Twist_R", "Upper Leg Twist_Right", "Leg Twist_R", "Leg Twist_Right", "Right Leg Twist"],
	"_013": ["Lower Leg_L", "Lower Leg_Left", "Left Lower Leg", "Knee_L", "Knee_Left", "Left Knee"],
	"_00f": ["Lower Leg_R", "Lower Leg_Right", "Right Lower Leg", "Knee_R", "Knee_Right", "Right Knee"],
	"_a13": ["Lower Leg Deform_L"],
	"_a0f": ["Lower Leg Deform_R"],
	"_014": ["Foot_L", "Foot_Left", "Left Foot", "Ankle_L", "Ankle_Left", "Left Ankle"],
	"_010": ["Foot_R", "Foot_Right", "Right Foot", "Ankle_R", "Ankle_Right", "Right Ankle"],
	"_a14": ["Foot Deform_L", "Foot Deform_Left", "Left Foot Deform", "Ankle Deform_L", "Ankle Deform_Left", "Left Ankle Deform", "Foot Twist_L", "Foot Twist_Left", "Left Foot Twist", "Ankle Twist_L", "Ankle Twist_Left", "Left Ankle Twist"],
	"_a10": ["Foot Deform_R", "Foot Deform_Right", "Right Foot Deform", "Ankle Deform_R", "Ankle Deform_Right", "Right Ankle Deform", "Foot Twist_R", "Foot Twist_Right", "Right Foot Twist", "Ankle Twist_R", "Ankle Twist_Right", "Right Ankle Twist"],
	"_015": ["Toes_L", "Toes_Left", "Left Toes"],
	"_011": ["Toes_R", "Toes_Right", "Right Toes"],
	"_8a0": ["Eye_L", "Eye_Left", "Left Eye", "Pupil_L", "Pupil_Left", "Left Pupil"],
	"_8a1": ["Eye_R", "Eye_Right", "Right Eye", "Pupil_R", "Pupil_Right", "Right Pupil"],
	"_840": ["Lid Top_00_L"],
    "_841": ["Lid Top_01_L"],
    "_842": ["Lid Top_02_L"],
    "_843": ["Lid Top_03_L"],
    "_84f": ["Lid Top_04_L"],
    "_848": ["Lid Bottom_01_L"],
    "_849": ["Lid Bottom_02_L"],
    "_84a": ["Lid Bottom_03_L"],
    "_850": ["Lid Top_00_R"],
    "_851": ["Lid Top_01_R"],
    "_852": ["Lid Top_02_R"],
    "_853": ["Lid Top_03_R"],
    "_85f": ["Lid Top_04_R"],
    "_858": ["Lid Bottom_01_R"],
    "_859": ["Lid Bottom_02_R"],
    "_85a": ["Lid Bottom_03_R"],
    "_830": ["Brow_01_L"],
    "_831": ["Brow_02_L"],
    "_832": ["Brow_03_L"],
    "_833": ["Brow_04_L"],
    "_838": ["Brow_01_R"],
    "_839": ["Brow_02_R"],
    "_83a": ["Brow_03_R"],
    "_83b": ["Brow_04_R"],
    "_886": ["Lip Top"],
    "_897": ["Lip Bottom"],
    "_890": ["Lip_L"],
    "_89f": ["Lip_R"],
    "_880": ["Lip Top_01_L"],
    "_881": ["Lip Top_02_L"],
    "_882": ["Lip Top_03_L"],
    "_883": ["Lip Top_04_L"],
    "_891": ["Lip Bottom_01_L"],
    "_892": ["Lip Bottom_02_L"],
    "_893": ["Lip Bottom_03_L"],
    "_894": ["Lip Bottom_04_L"],
    "_88c": ["Lip Top_01_R"],
    "_88b": ["Lip Top_02_R"],
    "_88a": ["Lip Top_03_R"],
    "_889": ["Lip Top_04_R"],
    "_89c": ["Lip Bottom_01_R"],
    "_89b": ["Lip Bottom_02_R"],
    "_89a": ["Lip Bottom_03_R"],
    "_899": ["Lip Bottom_04_R"],
    "_8b0": ["Teeth Top"],
    "_8b5": ["Teeth Bottom"],
    "_8b1": ["Teeth Top_L"],
    "_8b2": ["Teeth Top_R"],
    "_8b6": ["Teeth Bottom_L"],
    "_8b7": ["Teeth Bottom_R"],
    "_8c0": ["Tounge Base"],
    "_8c1": ["Tounge Middle"],
    "_8c2": ["Tounge Tip"],
    "_820": ["Mouth Inside Bottom"]
}

def get_bone_names_mapping():
    return BONE_NAME_MAPPINGS