# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .flatbuffers import *
from .flatbuffers.compat import import_numpy
np = import_numpy()

class ModelInfo_A11(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 28

    # ModelInfo_A11
    def Init(self, buf, pos):
        self._tab = table.Table(buf, pos)

    # ModelInfo_A11
    def A1(self): return self._tab.Get(number_types.Int32Flags, self._tab.Pos + number_types.UOffsetTFlags.py_type(0))
    # ModelInfo_A11
    def A2(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # ModelInfo_A11
    def A3(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj


def CreateModelInfo_A11(builder, a1, a2_x, a2_y, a2_z, a3_x, a3_y, a3_z):
    builder.Prep(4, 28)
    builder.Prep(4, 12)
    builder.PrependFloat32(a3_z)
    builder.PrependFloat32(a3_y)
    builder.PrependFloat32(a3_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(a2_z)
    builder.PrependFloat32(a2_y)
    builder.PrependFloat32(a2_x)
    builder.PrependInt32(a1)
    return builder.Offset()
