# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

class BgReactionData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BgReactionData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBgReactionData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BgReactionData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BgReactionData
    def HitHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BgReactionData
    def HitRadius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BgReactionData
    def ParticleType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BgReactionData
    def PlaySound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BgReactionDataStart(builder):
    builder.StartObject(4)

def Start(builder):
    BgReactionDataStart(builder)

def BgReactionDataAddHitHeight(builder, hitHeight):
    builder.PrependFloat32Slot(0, hitHeight, 0.0)

def AddHitHeight(builder, hitHeight):
    BgReactionDataAddHitHeight(builder, hitHeight)

def BgReactionDataAddHitRadius(builder, hitRadius):
    builder.PrependFloat32Slot(1, hitRadius, 0.0)

def AddHitRadius(builder, hitRadius):
    BgReactionDataAddHitRadius(builder, hitRadius)

def BgReactionDataAddParticleType(builder, particleType):
    builder.PrependInt8Slot(2, particleType, 0)

def AddParticleType(builder, particleType):
    BgReactionDataAddParticleType(builder, particleType)

def BgReactionDataAddPlaySound(builder, playSound):
    builder.PrependBoolSlot(3, playSound, 0)

def AddPlaySound(builder, playSound):
    BgReactionDataAddPlaySound(builder, playSound)

def BgReactionDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return BgReactionDataEnd(builder)
