# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

#//////////////
#//////////////
class BufferLocator(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # BufferLocator
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BufferLocator
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BufferLocator
    def Size(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateBufferLocator(builder, offset, size):
    builder.Prep(8, 16)
    builder.PrependUint64(size)
    builder.PrependUint64(offset)
    return builder.Offset()
