# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

class LODChunk(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # LODChunk
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LODChunk
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # LODChunk
    def Count(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # LODChunk
    def MeshId(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # LODChunk
    def MaterialId(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(9))
    # LODChunk
    def A5(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # LODChunk
    def A6(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(11))

def CreateLODChunk(builder, offset, count, meshId, materialId, a5, a6):
    builder.Prep(4, 12)
    builder.PrependInt8(a6)
    builder.PrependInt8(a5)
    builder.PrependInt8(materialId)
    builder.PrependInt8(meshId)
    builder.PrependInt32(count)
    builder.PrependInt32(offset)
    return builder.Offset()
