# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

class MaterialInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MaterialInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMaterialInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MaterialInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MaterialInfo
    def UniqueNameHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MaterialInfo
    def MaterialFlags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def MaterialInfoStart(builder):
    builder.StartObject(2)

def Start(builder):
    MaterialInfoStart(builder)

def MaterialInfoAddUniqueNameHash(builder, uniqueNameHash):
    builder.PrependUint32Slot(0, uniqueNameHash, 0)

def AddUniqueNameHash(builder, uniqueNameHash):
    MaterialInfoAddUniqueNameHash(builder, uniqueNameHash)

def MaterialInfoAddMaterialFlags(builder, materialFlags):
    builder.PrependInt8Slot(1, materialFlags, 0)

def AddMaterialFlags(builder, materialFlags):
    MaterialInfoAddMaterialFlags(builder, materialFlags)

def MaterialInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return MaterialInfoEnd(builder)
