# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

class MeshInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeshInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeshInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MeshInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeshInfo
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MeshInfo
    def Bbox(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .BoundaryBox import BoundaryBox
            obj = BoundaryBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MeshInfoStart(builder):
    builder.StartObject(2)

def Start(builder):
    MeshInfoStart(builder)

def MeshInfoAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    MeshInfoAddName(builder, name)

def MeshInfoAddBbox(builder, bbox):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bbox), 0)

def AddBbox(builder, bbox):
    MeshInfoAddBbox(builder, bbox)

def MeshInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return MeshInfoEnd(builder)
