# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

class ModelInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelInfo
    def Magic(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def Lods(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .StreamLOD import StreamLOD
            obj = StreamLOD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def LodsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def LodsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ModelInfo
    def ShadowLods(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .StreamLOD import StreamLOD
            obj = StreamLOD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def ShadowLodsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def ShadowLodsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ModelInfo
    def LodScreenSizeThresholds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ModelInfo
    def LodScreenSizeThresholdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ModelInfo
    def LodScreenSizeThresholdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def LodScreenSizeThresholdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ModelInfo
    def Meshes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .MeshInfo import MeshInfo
            obj = MeshInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def MeshesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def MeshesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ModelInfo
    def Materials(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .MaterialInfo import MaterialInfo
            obj = MaterialInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def MaterialsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def MaterialsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ModelInfo
    def DeformBoneToBoneIndexTable(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # ModelInfo
    def DeformBoneToBoneIndexTableAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ModelInfo
    def DeformBoneToBoneIndexTableLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def DeformBoneToBoneIndexTableIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ModelInfo
    def DeformBoneBoundaryBox(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from .BoundaryBox import BoundaryBox
            obj = BoundaryBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def DeformBoneBoundaryBoxLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def DeformBoneBoundaryBoxIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # ModelInfo
    def BoundingSphere(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec4 import Vec4
            obj = Vec4()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def BgReactionData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .BgReactionData import BgReactionData
            obj = BgReactionData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def Vec311(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def NearCameraBoundRadius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def NearCameraDetectionScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def FadeOutDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F15(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F16(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F17(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F18(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F19(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def U20(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def Byte21(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def SceneGraphMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def UseSceneGraphCache(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool24(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def IsShip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool26(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def UseBoneBoundsForFade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool28(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool29(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def ForceNearFadeEvaluation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool31(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def UseMeshAabbForFade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def RenderFlags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def CameraNearFadeAabbRadius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ModelInfoStart(builder):
    builder.StartObject(34)

def Start(builder):
    ModelInfoStart(builder)

def ModelInfoAddMagic(builder, magic):
    builder.PrependUint32Slot(0, magic, 0)

def AddMagic(builder, magic):
    ModelInfoAddMagic(builder, magic)

def ModelInfoAddLods(builder, lods):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(lods), 0)

def AddLods(builder, lods):
    ModelInfoAddLods(builder, lods)

def ModelInfoStartLodsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLodsVector(builder, numElems):
    return ModelInfoStartLodsVector(builder, numElems)

def ModelInfoAddShadowLods(builder, shadowLods):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(shadowLods), 0)

def AddShadowLods(builder, shadowLods):
    ModelInfoAddShadowLods(builder, shadowLods)

def ModelInfoStartShadowLodsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShadowLodsVector(builder, numElems):
    return ModelInfoStartShadowLodsVector(builder, numElems)

def ModelInfoAddLodScreenSizeThresholds(builder, lodScreenSizeThresholds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(lodScreenSizeThresholds), 0)

def AddLodScreenSizeThresholds(builder, lodScreenSizeThresholds):
    ModelInfoAddLodScreenSizeThresholds(builder, lodScreenSizeThresholds)

def ModelInfoStartLodScreenSizeThresholdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLodScreenSizeThresholdsVector(builder, numElems):
    return ModelInfoStartLodScreenSizeThresholdsVector(builder, numElems)

def ModelInfoAddMeshes(builder, meshes):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(meshes), 0)

def AddMeshes(builder, meshes):
    ModelInfoAddMeshes(builder, meshes)

def ModelInfoStartMeshesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMeshesVector(builder, numElems):
    return ModelInfoStartMeshesVector(builder, numElems)

def ModelInfoAddMaterials(builder, materials):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(materials), 0)

def AddMaterials(builder, materials):
    ModelInfoAddMaterials(builder, materials)

def ModelInfoStartMaterialsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMaterialsVector(builder, numElems):
    return ModelInfoStartMaterialsVector(builder, numElems)

def ModelInfoAddDeformBoneToBoneIndexTable(builder, deformBoneToBoneIndexTable):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(deformBoneToBoneIndexTable), 0)

def AddDeformBoneToBoneIndexTable(builder, deformBoneToBoneIndexTable):
    ModelInfoAddDeformBoneToBoneIndexTable(builder, deformBoneToBoneIndexTable)

def ModelInfoStartDeformBoneToBoneIndexTableVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartDeformBoneToBoneIndexTableVector(builder, numElems):
    return ModelInfoStartDeformBoneToBoneIndexTableVector(builder, numElems)

def ModelInfoAddDeformBoneBoundaryBox(builder, deformBoneBoundaryBox):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(deformBoneBoundaryBox), 0)

def AddDeformBoneBoundaryBox(builder, deformBoneBoundaryBox):
    ModelInfoAddDeformBoneBoundaryBox(builder, deformBoneBoundaryBox)

def ModelInfoStartDeformBoneBoundaryBoxVector(builder, numElems):
    return builder.StartVector(24, numElems, 4)

def StartDeformBoneBoundaryBoxVector(builder, numElems):
    return ModelInfoStartDeformBoneBoundaryBoxVector(builder, numElems)

def ModelInfoAddBoundingSphere(builder, boundingSphere):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(boundingSphere), 0)

def AddBoundingSphere(builder, boundingSphere):
    ModelInfoAddBoundingSphere(builder, boundingSphere)

def ModelInfoAddBgReactionData(builder, bgReactionData):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(bgReactionData), 0)

def AddBgReactionData(builder, bgReactionData):
    ModelInfoAddBgReactionData(builder, bgReactionData)

def ModelInfoAddVec311(builder, vec311):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(vec311), 0)

def AddVec311(builder, vec311):
    ModelInfoAddVec311(builder, vec311)

def ModelInfoAddNearCameraBoundRadius(builder, nearCameraBoundRadius):
    builder.PrependFloat32Slot(11, nearCameraBoundRadius, 0.0)

def AddNearCameraBoundRadius(builder, nearCameraBoundRadius):
    ModelInfoAddNearCameraBoundRadius(builder, nearCameraBoundRadius)

def ModelInfoAddNearCameraDetectionScale(builder, nearCameraDetectionScale):
    builder.PrependFloat32Slot(12, nearCameraDetectionScale, 0.0)

def AddNearCameraDetectionScale(builder, nearCameraDetectionScale):
    ModelInfoAddNearCameraDetectionScale(builder, nearCameraDetectionScale)

def ModelInfoAddFadeOutDistance(builder, fadeOutDistance):
    builder.PrependFloat32Slot(13, fadeOutDistance, 0.0)

def AddFadeOutDistance(builder, fadeOutDistance):
    ModelInfoAddFadeOutDistance(builder, fadeOutDistance)

def ModelInfoAddF15(builder, f15):
    builder.PrependFloat32Slot(14, f15, 0.0)

def AddF15(builder, f15):
    ModelInfoAddF15(builder, f15)

def ModelInfoAddF16(builder, f16):
    builder.PrependFloat32Slot(15, f16, 0.0)

def AddF16(builder, f16):
    ModelInfoAddF16(builder, f16)

def ModelInfoAddF17(builder, f17):
    builder.PrependFloat32Slot(16, f17, 0.0)

def AddF17(builder, f17):
    ModelInfoAddF17(builder, f17)

def ModelInfoAddF18(builder, f18):
    builder.PrependFloat32Slot(17, f18, 0.0)

def AddF18(builder, f18):
    ModelInfoAddF18(builder, f18)

def ModelInfoAddF19(builder, f19):
    builder.PrependFloat32Slot(18, f19, 0.0)

def AddF19(builder, f19):
    ModelInfoAddF19(builder, f19)

def ModelInfoAddU20(builder, u20):
    builder.PrependUint32Slot(19, u20, 0)

def AddU20(builder, u20):
    ModelInfoAddU20(builder, u20)

def ModelInfoAddByte21(builder, byte21):
    builder.PrependInt8Slot(20, byte21, 0)

def AddByte21(builder, byte21):
    ModelInfoAddByte21(builder, byte21)

def ModelInfoAddSceneGraphMode(builder, sceneGraphMode):
    builder.PrependInt8Slot(21, sceneGraphMode, 0)

def AddSceneGraphMode(builder, sceneGraphMode):
    ModelInfoAddSceneGraphMode(builder, sceneGraphMode)

def ModelInfoAddUseSceneGraphCache(builder, useSceneGraphCache):
    builder.PrependBoolSlot(22, useSceneGraphCache, 0)

def AddUseSceneGraphCache(builder, useSceneGraphCache):
    ModelInfoAddUseSceneGraphCache(builder, useSceneGraphCache)

def ModelInfoAddBool24(builder, bool24):
    builder.PrependBoolSlot(23, bool24, 0)

def AddBool24(builder, bool24):
    ModelInfoAddBool24(builder, bool24)

def ModelInfoAddIsShip(builder, isShip):
    builder.PrependBoolSlot(24, isShip, 0)

def AddIsShip(builder, isShip):
    ModelInfoAddIsShip(builder, isShip)

def ModelInfoAddBool26(builder, bool26):
    builder.PrependBoolSlot(25, bool26, 0)

def AddBool26(builder, bool26):
    ModelInfoAddBool26(builder, bool26)

def ModelInfoAddUseBoneBoundsForFade(builder, useBoneBoundsForFade):
    builder.PrependBoolSlot(26, useBoneBoundsForFade, 0)

def AddUseBoneBoundsForFade(builder, useBoneBoundsForFade):
    ModelInfoAddUseBoneBoundsForFade(builder, useBoneBoundsForFade)

def ModelInfoAddBool28(builder, bool28):
    builder.PrependBoolSlot(27, bool28, 0)

def AddBool28(builder, bool28):
    ModelInfoAddBool28(builder, bool28)

def ModelInfoAddBool29(builder, bool29):
    builder.PrependBoolSlot(28, bool29, 0)

def AddBool29(builder, bool29):
    ModelInfoAddBool29(builder, bool29)

def ModelInfoAddForceNearFadeEvaluation(builder, forceNearFadeEvaluation):
    builder.PrependBoolSlot(29, forceNearFadeEvaluation, 0)

def AddForceNearFadeEvaluation(builder, forceNearFadeEvaluation):
    ModelInfoAddForceNearFadeEvaluation(builder, forceNearFadeEvaluation)

def ModelInfoAddBool31(builder, bool31):
    builder.PrependInt8Slot(30, bool31, 0)

def AddBool31(builder, bool31):
    ModelInfoAddBool31(builder, bool31)

def ModelInfoAddUseMeshAabbForFade(builder, useMeshAabbForFade):
    builder.PrependBoolSlot(31, useMeshAabbForFade, 0)

def AddUseMeshAabbForFade(builder, useMeshAabbForFade):
    ModelInfoAddUseMeshAabbForFade(builder, useMeshAabbForFade)

def ModelInfoAddRenderFlags(builder, renderFlags):
    builder.PrependInt8Slot(32, renderFlags, 0)

def AddRenderFlags(builder, renderFlags):
    ModelInfoAddRenderFlags(builder, renderFlags)

def ModelInfoAddCameraNearFadeAabbRadius(builder, cameraNearFadeAabbRadius):
    builder.PrependFloat32Slot(33, cameraNearFadeAabbRadius, 0.0)

def AddCameraNearFadeAabbRadius(builder, cameraNearFadeAabbRadius):
    ModelInfoAddCameraNearFadeAabbRadius(builder, cameraNearFadeAabbRadius)

def ModelInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelInfoEnd(builder)
