# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

class ModelInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelInfo
    def Magic(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def Lods(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .StreamLOD import StreamLOD
            obj = StreamLOD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def LodsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def LodsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ModelInfo
    def ShadowLods(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .StreamLOD import StreamLOD
            obj = StreamLOD()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def ShadowLodsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def ShadowLodsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ModelInfo
    def A4(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ModelInfo
    def A4AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ModelInfo
    def A4Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def A4IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ModelInfo
    def Meshes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .MeshInfo import MeshInfo
            obj = MeshInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def MeshesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def MeshesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ModelInfo
    def Materials(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .MaterialInfo import MaterialInfo
            obj = MaterialInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def MaterialsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def MaterialsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ModelInfo
    def BonesToWeightIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # ModelInfo
    def BonesToWeightIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ModelInfo
    def BonesToWeightIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def BonesToWeightIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ModelInfo
    def DeformBoneBoundaryBox(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from .BoundaryBox import BoundaryBox
            obj = BoundaryBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def DeformBoneBoundaryBoxLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelInfo
    def DeformBoneBoundaryBoxIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # ModelInfo
    def Vec39(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def BgReactionData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .BgReactionData import BgReactionData
            obj = BgReactionData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def Vec311(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelInfo
    def F12(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F13(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def FadeOutDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F15(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F16(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F17(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F18(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def F19(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ModelInfo
    def U20(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def Byte21(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def Byte22(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def Bool23(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool24(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def IsShip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool26(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool27(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool28(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool29(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool30(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool31(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool32(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ModelInfo
    def Bool33(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelInfo
    def Float34(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ModelInfoStart(builder):
    builder.StartObject(34)

def Start(builder):
    ModelInfoStart(builder)

def ModelInfoAddMagic(builder, magic):
    builder.PrependUint32Slot(0, magic, 0)

def AddMagic(builder, magic):
    ModelInfoAddMagic(builder, magic)

def ModelInfoAddLods(builder, lods):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(lods), 0)

def AddLods(builder, lods):
    ModelInfoAddLods(builder, lods)

def ModelInfoStartLodsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLodsVector(builder, numElems):
    return ModelInfoStartLodsVector(builder, numElems)

def ModelInfoAddShadowLods(builder, shadowLods):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(shadowLods), 0)

def AddShadowLods(builder, shadowLods):
    ModelInfoAddShadowLods(builder, shadowLods)

def ModelInfoStartShadowLodsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShadowLodsVector(builder, numElems):
    return ModelInfoStartShadowLodsVector(builder, numElems)

def ModelInfoAddA4(builder, a4):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(a4), 0)

def AddA4(builder, a4):
    ModelInfoAddA4(builder, a4)

def ModelInfoStartA4Vector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartA4Vector(builder, numElems):
    return ModelInfoStartA4Vector(builder, numElems)

def ModelInfoAddMeshes(builder, meshes):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(meshes), 0)

def AddMeshes(builder, meshes):
    ModelInfoAddMeshes(builder, meshes)

def ModelInfoStartMeshesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMeshesVector(builder, numElems):
    return ModelInfoStartMeshesVector(builder, numElems)

def ModelInfoAddMaterials(builder, materials):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(materials), 0)

def AddMaterials(builder, materials):
    ModelInfoAddMaterials(builder, materials)

def ModelInfoStartMaterialsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMaterialsVector(builder, numElems):
    return ModelInfoStartMaterialsVector(builder, numElems)

def ModelInfoAddBonesToWeightIndices(builder, bonesToWeightIndices):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(bonesToWeightIndices), 0)

def AddBonesToWeightIndices(builder, bonesToWeightIndices):
    ModelInfoAddBonesToWeightIndices(builder, bonesToWeightIndices)

def ModelInfoStartBonesToWeightIndicesVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartBonesToWeightIndicesVector(builder, numElems):
    return ModelInfoStartBonesToWeightIndicesVector(builder, numElems)

def ModelInfoAddDeformBoneBoundaryBox(builder, deformBoneBoundaryBox):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(deformBoneBoundaryBox), 0)

def AddDeformBoneBoundaryBox(builder, deformBoneBoundaryBox):
    ModelInfoAddDeformBoneBoundaryBox(builder, deformBoneBoundaryBox)

def ModelInfoStartDeformBoneBoundaryBoxVector(builder, numElems):
    return builder.StartVector(24, numElems, 4)

def StartDeformBoneBoundaryBoxVector(builder, numElems):
    return ModelInfoStartDeformBoneBoundaryBoxVector(builder, numElems)

def ModelInfoAddVec39(builder, vec39):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(vec39), 0)

def AddVec39(builder, vec39):
    ModelInfoAddVec39(builder, vec39)

def ModelInfoAddBgReactionData(builder, bgReactionData):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(bgReactionData), 0)

def AddBgReactionData(builder, bgReactionData):
    ModelInfoAddBgReactionData(builder, bgReactionData)

def ModelInfoAddVec311(builder, vec311):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(vec311), 0)

def AddVec311(builder, vec311):
    ModelInfoAddVec311(builder, vec311)

def ModelInfoAddF12(builder, f12):
    builder.PrependFloat32Slot(11, f12, 0.0)

def AddF12(builder, f12):
    ModelInfoAddF12(builder, f12)

def ModelInfoAddF13(builder, f13):
    builder.PrependFloat32Slot(12, f13, 0.0)

def AddF13(builder, f13):
    ModelInfoAddF13(builder, f13)

def ModelInfoAddFadeOutDistance(builder, fadeOutDistance):
    builder.PrependFloat32Slot(13, fadeOutDistance, 0.0)

def AddFadeOutDistance(builder, fadeOutDistance):
    ModelInfoAddFadeOutDistance(builder, fadeOutDistance)

def ModelInfoAddF15(builder, f15):
    builder.PrependFloat32Slot(14, f15, 0.0)

def AddF15(builder, f15):
    ModelInfoAddF15(builder, f15)

def ModelInfoAddF16(builder, f16):
    builder.PrependFloat32Slot(15, f16, 0.0)

def AddF16(builder, f16):
    ModelInfoAddF16(builder, f16)

def ModelInfoAddF17(builder, f17):
    builder.PrependFloat32Slot(16, f17, 0.0)

def AddF17(builder, f17):
    ModelInfoAddF17(builder, f17)

def ModelInfoAddF18(builder, f18):
    builder.PrependFloat32Slot(17, f18, 0.0)

def AddF18(builder, f18):
    ModelInfoAddF18(builder, f18)

def ModelInfoAddF19(builder, f19):
    builder.PrependFloat32Slot(18, f19, 0.0)

def AddF19(builder, f19):
    ModelInfoAddF19(builder, f19)

def ModelInfoAddU20(builder, u20):
    builder.PrependUint32Slot(19, u20, 0)

def AddU20(builder, u20):
    ModelInfoAddU20(builder, u20)

def ModelInfoAddByte21(builder, byte21):
    builder.PrependInt8Slot(20, byte21, 0)

def AddByte21(builder, byte21):
    ModelInfoAddByte21(builder, byte21)

def ModelInfoAddByte22(builder, byte22):
    builder.PrependInt8Slot(21, byte22, 0)

def AddByte22(builder, byte22):
    ModelInfoAddByte22(builder, byte22)

def ModelInfoAddBool23(builder, bool23):
    builder.PrependBoolSlot(22, bool23, 0)

def AddBool23(builder, bool23):
    ModelInfoAddBool23(builder, bool23)

def ModelInfoAddBool24(builder, bool24):
    builder.PrependBoolSlot(23, bool24, 0)

def AddBool24(builder, bool24):
    ModelInfoAddBool24(builder, bool24)

def ModelInfoAddIsShip(builder, isShip):
    builder.PrependBoolSlot(24, isShip, 0)

def AddIsShip(builder, isShip):
    ModelInfoAddIsShip(builder, isShip)

def ModelInfoAddBool26(builder, bool26):
    builder.PrependBoolSlot(25, bool26, 0)

def AddBool26(builder, bool26):
    ModelInfoAddBool26(builder, bool26)

def ModelInfoAddBool27(builder, bool27):
    builder.PrependBoolSlot(26, bool27, 0)

def AddBool27(builder, bool27):
    ModelInfoAddBool27(builder, bool27)

def ModelInfoAddBool28(builder, bool28):
    builder.PrependBoolSlot(27, bool28, 0)

def AddBool28(builder, bool28):
    ModelInfoAddBool28(builder, bool28)

def ModelInfoAddBool29(builder, bool29):
    builder.PrependBoolSlot(28, bool29, 0)

def AddBool29(builder, bool29):
    ModelInfoAddBool29(builder, bool29)

def ModelInfoAddBool30(builder, bool30):
    builder.PrependBoolSlot(29, bool30, 0)

def AddBool30(builder, bool30):
    ModelInfoAddBool30(builder, bool30)

def ModelInfoAddBool31(builder, bool31):
    builder.PrependBoolSlot(30, bool31, 0)

def AddBool31(builder, bool31):
    ModelInfoAddBool31(builder, bool31)

def ModelInfoAddBool32(builder, bool32):
    builder.PrependBoolSlot(31, bool32, 0)

def AddBool32(builder, bool32):
    ModelInfoAddBool32(builder, bool32)

def ModelInfoAddBool33(builder, bool33):
    builder.PrependInt8Slot(32, bool33, 0)

def AddBool33(builder, bool33):
    ModelInfoAddBool33(builder, bool33)

def ModelInfoAddFloat34(builder, float34):
    builder.PrependFloat32Slot(33, float34, 0.0)

def AddFloat34(builder, float34):
    ModelInfoAddFloat34(builder, float34)

def ModelInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelInfoEnd(builder)
