# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

from .. import flatbuffers
from ..flatbuffers.compat import import_numpy
np = import_numpy()

class StreamLOD(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StreamLOD()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStreamLOD(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StreamLOD
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StreamLOD
    def Buffers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from .BufferLocator import BufferLocator
            obj = BufferLocator()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StreamLOD
    def BuffersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StreamLOD
    def BuffersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # StreamLOD
    def Chunks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from .LODChunk import LODChunk
            obj = LODChunk()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StreamLOD
    def ChunksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StreamLOD
    def ChunksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # StreamLOD
    def VertexCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StreamLOD
    def IndexCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StreamLOD
    def BufferTypes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # StreamLOD
    def A6(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def StreamLODStart(builder):
    builder.StartObject(6)

def Start(builder):
    StreamLODStart(builder)

def StreamLODAddBuffers(builder, buffers):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(buffers), 0)

def AddBuffers(builder, buffers):
    StreamLODAddBuffers(builder, buffers)

def StreamLODStartBuffersVector(builder, numElems):
    return builder.StartVector(16, numElems, 8)

def StartBuffersVector(builder, numElems):
    return StreamLODStartBuffersVector(builder, numElems)

def StreamLODAddChunks(builder, chunks):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(chunks), 0)

def AddChunks(builder, chunks):
    StreamLODAddChunks(builder, chunks)

def StreamLODStartChunksVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartChunksVector(builder, numElems):
    return StreamLODStartChunksVector(builder, numElems)

def StreamLODAddVertexCount(builder, vertexCount):
    builder.PrependInt32Slot(2, vertexCount, 0)

def AddVertexCount(builder, vertexCount):
    StreamLODAddVertexCount(builder, vertexCount)

def StreamLODAddIndexCount(builder, indexCount):
    builder.PrependInt32Slot(3, indexCount, 0)

def AddIndexCount(builder, indexCount):
    StreamLODAddIndexCount(builder, indexCount)

def StreamLODAddBufferTypes(builder, bufferTypes):
    builder.PrependUint8Slot(4, bufferTypes, 0)

def AddBufferTypes(builder, bufferTypes):
    StreamLODAddBufferTypes(builder, bufferTypes)

def StreamLODAddA6(builder, a6):
    builder.PrependUint8Slot(5, a6, 0)

def AddA6(builder, a6):
    StreamLODAddA6(builder, a6)

def StreamLODEnd(builder):
    return builder.EndObject()

def End(builder):
    return StreamLODEnd(builder)
