# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Entities

class VertexBufferType(object):
    POS_NOR_TAN_UV0 = 1
    BLENDINDICES = 2
    BLENDINDICES_2 = 4
    BLENDWEIGHT = 8
    BLENDWEIGHT_2 = 16
    COLOR = 32
    TEXCOORD = 64
